### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by adricarda** [Raykoooo/IAST#1]
Hi, when the code will be released?

**Comment by Siddharth-Shrivastava7** [comment]
Hi @Raykoooo, could you please let us know when you will make your code available?

**Comment by Siddharth-Shrivastava7** [comment]
Hi @Raykoooo, I would request you too to let us know when will be open-sourcing your code?

**Comment by Siddharth-Shrivastava7** [comment]
Hi @Raykoooo, I would request you too to let us know when you will be open-sourcing your code?

**Comment by Amandaynzhou** [comment]
Hi, 
Very impressive work on UDA and SSL segmentation. Looking forward to the code releases!

**Comment by Raykoooo** [comment]
Reply to all:
Thank you for your attention to this work. I have released the complete code.
Please let me know if there are any problems or bugs, thank you.
