### ISSUE TITLE
training on novel dataset

### ISSUE THREAD

**Issue by PolarBean** [Raykoooo/IAST#12]
Hey, great paper! any advice on how to train IAST on a new dataset?

**Comment by super233** [comment]
Sorry for the late reply, thank you for your attention to our paper.

For training IAST on a new dataset, please follow the following steps:
1. Generate a JSON file where each item should contain `image_name` and `mask_name`, which indicate the relative path of image and label. For more details, please see the JSON files in `IAST/data`.
2. Implement a dataset class that inherits the `BaseDataset`, just like the `MsCityscapesDataset`, and overwrite the `transform_mask(self, label)` for specific label transformation and `aug(self, image, label)` for the augmentation. Last but not least, please register your dataset with a customized name by using `@DATASET.register("your_dataset_name")`.
https://github.com/Raykoooo/IAST/blob/24db9912403a01faf34884d60c9778cd48651bde/code/sseg/datasets/loader/cityscapes_dataset.py#L17-L25

I hope this can help you, I close this issue, if you have any other questions, please comment and I will reopen it.
