### ISSUE TITLE
Are the miou results described in the paper a single stage result? (synthia->cityscapes)

### ISSUE THREAD

**Issue by wonhuee** [Raykoooo/IAST#13]
Hello, thanks for your amazing works.

I wonder if the miou result of your method for synthia->cityscapes (Table 7 in your paper) is a single stage result or multi-stage result.
If the performance is result of single stage, can you tell the miou result when performing multi-stage?

Thank you.

**Comment by super233** [comment]
The results presented in our paper were obtained by multi-round training. :-)

**Comment by wonhuee** [comment]
Thank you for your replying:)

I also want you to ask what is the difference between "IAST(ours)" and "IAST-MST(ours)" below table (Table 6 in your paper)? 

I thought that "IAST(ours)" is the result of single-stage and "IAST-MST(ours)" is for the result of multi-round training.

If above thought is right, can I understand that the "IAST-MST(ours)" in Table 6 & "IAST(ours)" in Table 7 are obtained by multi-round training and "IAST(ours)" in Table 6 is obtained by single stage training?

Thank you.

![image](https://user-images.githubusercontent.com/107539482/173880132-c4f0ee6b-ff09-4eeb-973e-ca6b81c9374c.png)

**Comment by super233** [comment]
We are sorry for lacking a description of "MST" in our paper. 

"MST" means that the model was evaluated under multiple scales setting, where an image with different sizes was fed into the model, and their outputs were summed for the final predictions. "MST" was first used in [FADA](http://arxiv.org/abs/2007.09222) (see the caption of Table 4 in FADA). For more implementation details, please see the [code snippets](https://github.com/Raykoooo/IAST/blob/24db9912403a01faf34884d60c9778cd48651bde/code/sseg/workflow/eval.py#L81-L91).

I should emphasize again that all results in our paper were obtained by multi-round training. :-)

**Comment by wonhuee** [comment]
Thank you for your clear explanation :)
