### ISSUE TITLE
Running Error

### ISSUE THREAD

**Issue by JiahuaDong** [Raykoooo/IAST#2]
hi， Thanks for sharing teh code!
When running the code, I have the bug: "No module named apex"
Could you please provide the corresponding file "apex.parallel" in the trainer file??
Thans for your reply!

**Comment by Raykoooo** [comment]
I guess you did not install apex correctly.
`apex` :  Tools for easy mixed precision and distributed training in Pytorch. 
```
git clone https://github.com/NVIDIA/apex
cd apex
pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
```
More details: https://github.com/NVIDIA/apex

**Comment by JiahuaDong** [comment]
@Raykoooo   Thanks for your reply.  When runing the training file from scratch,  another bug  still confuses me:
AssertionError: cfg.MODEL.DECODER.TYPE: DeepLabV2Decoder are not registered in registry 
How to register it?
Thanks for your help.

**Comment by Raykoooo** [comment]
> @Raykoooo Thanks for your reply. When runing the training file from scratch, another bug still confuses me:
> AssertionError: cfg.MODEL.DECODER.TYPE: DeepLabV2Decoder are not registered in registry
> How to register it?
> Thanks for your help.

Please check your `code/main.py`:
```
from sseg.models.decoder import deeplabv2_decoder
```
Then DeepLabV2Decoder will be registered.
