### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by lrjing** [Raykoooo/IAST#5]
Hello, thank you very much for your open source code.
Because of the limited capacity of the GPU, I can only use the weights that you trained with the graphics card T4.
I ran the GTA5 dataset and it was similar to yours.
This is because GitHub has not yet updated the weight of T4 for the Synthia dataset. So I trained this part from scratch.When I started training from scratch, I found that the results were a little poor.I don't understand this question, so I want to consult you.I would also like to ask when you can update the training weights for the Synthia dataset.
Thank you very much.

**Comment by Raykoooo** [comment]
When using the Synthia dataset, the miou in the log is the mean of the 19 categories, while the miou reported in the paper is the 16/13 category. You need to calculate them manually.

**Comment by super233** [comment]
@lrjing We have rerun "SYNTHIA to Cityscapes" on 2 "Tesla T4", and updated the model download link, please check it.
