### ISSUE TITLE
cannot reproduce the result

### ISSUE THREAD

**Issue by liyunsheng13** [Raykoooo/IAST#6]
Hi
I try to implement the release code on T4 for GTA5->Cityscapes and found  the best result I can get is 50.7, which happens in the sl_1 and I saw overfitting problem and finally get 49.5 for sl_3. I wonder whether you have similar results and only report the best one during all the training process.

Thanks

**Comment by Raykoooo** [comment]
Yes, I report the best one. Actually, my experiments are all done on V100. The result I ran on T4 was 51.2, without careful parameter adjustment.

**Comment by liyunsheng13** [comment]
Thanks for your response. Another question is about image resolution. I think you used 2048x1024 but for most of the works I think they downsample the image to 1024x512, have you tried this resolution to make a fair comparison?

**Comment by super233** [comment]
@liyunsheng13 The image resolution for training has been fixed to [1024, 512] by augmentation, just see: 
https://github.com/Raykoooo/IAST/blob/2eadc081c810b6780fd046d17401083a816e64f5/code/sseg/datasets/loader/cityscapes_dataset.py#L14 https://github.com/Raykoooo/IAST/blob/2eadc081c810b6780fd046d17401083a816e64f5/code/sseg/datasets/loader/cityscapes_dataset.py#L25 https://github.com/Raykoooo/IAST/blob/2eadc081c810b6780fd046d17401083a816e64f5/code/sseg/datasets/loader/gtav_dataset.py#L20 https://github.com/Raykoooo/IAST/blob/2eadc081c810b6780fd046d17401083a816e64f5/code/sseg/datasets/loader/gtav_dataset.py#L36 https://github.com/Raykoooo/IAST/blob/2eadc081c810b6780fd046d17401083a816e64f5/code/sseg/datasets/loader/synthia_dataset.py#L32 https://github.com/Raykoooo/IAST/blob/2eadc081c810b6780fd046d17401083a816e64f5/code/sseg/datasets/loader/synthia_dataset.py#L101

And the author has clarified this in "Implementation details": 
![image](https://user-images.githubusercontent.com/35358984/124309533-6f626580-db9d-11eb-8e6b-dc69c1e41de8.png)
