### ISSUE TITLE
About model selection

### ISSUE THREAD

**Issue by Songzc0** [Raykoooo/IAST#7]
https://github.com/Raykoooo/IAST/blob/a10bee6ee4b814ef5dc5c85071aedfcac1e367a8/scripts/self_training_only/run_gtav2cityscapes_self_traing_only_t4.sh#L7

Thanks for your good work and the code. In the configuration files, is there any special reason to use the model after first epoch for the pseudo label generation but resume from the last model for the next round?

**Comment by super233** [comment]
@Songzc0 The author can answer the question better, the task is **unsupervised** domain adaptation, we can not know when the model is the best, and this may be a trade-off to get better results in the subsequent stages.
